export const STORE_RISK_MAP: Record<string, 'High' | 'Medium' | 'Low'> = {
  '1':  'High',
  '2':  'Medium',
  '3':  'Low',
  '4':  'Medium',
  '5':  'Medium',
  '6':  'Medium',
  '7':  'Medium',
  '8':  'Low',
  '9':  'High',
  '10': 'Low',
  '11': 'High',
  '12': 'Medium',
  '13': 'High',
  '14': 'Medium',
  '15': 'High',
  '16': 'Low',
  '17': 'Medium',
  '18': 'Medium',
  '19': 'Medium',
  '20': 'Medium',
  '21': 'Low',
  '22': 'High',
  '23': 'Low',
}
